compile fix for gcc 4.6.*
avr-gcc 4.6.* complaint:
avr-gcc -Wall -W -Wno-unused-parameter -Wno-sign-compare -Wno-char-subscripts -g -Os -std=gnu99 -fdata-sections -ffunction-sections -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -mcall-prologues -fshort-enums -fno-strict-aliasing -Iprotocols/usb/usbdrv -Iprotocols/usb -DAVR_BUILD -DF_CPU=20000000UL -mmcu=atmega644 -I.  -c -o services/watchasync/watchasync.o services/watchasync/watchasync.c
In file included from services/watchasync/watchasync.c:55:0:
./services/watchasync/watchasync_strings.c:146:19: error: variable 'watchasync_ID' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
make: *** [services/watchasync/watchasync.o] Error 1